# Distance Optimization Configuration for OAM 6G Systems

# Distance thresholds for mode selection
distance_thresholds:
  near_threshold: 50.0      # meters - optimal for modes 1-3
  medium_threshold: 150.0    # meters - optimal for modes 4-6
  far_threshold: 300.0       # meters - optimal for modes 7-8

# Mode preferences by distance category
mode_preferences:
  near_modes: [1, 2, 3]     # Lower modes for near distances (better beam focus)
  medium_modes: [4, 5, 6]   # Medium modes for medium distances (balanced performance)
  far_modes: [7, 8]         # Higher modes for far distances (better coverage)

# Optimization weights for multi-criteria optimization
optimization_weights:
  distance_weight: 0.3       # Weight of distance in optimization
  throughput_weight: 0.5     # Weight of throughput in optimization
  stability_weight: 0.2      # Weight of stability in optimization

# Adaptive threshold parameters
adaptive_parameters:
  enabled: true              # Enable adaptive threshold adjustment
  learning_rate: 0.01        # Learning rate for adaptive thresholds
  min_threshold: 50.0        # Minimum threshold value
  max_threshold: 400.0       # Maximum threshold value

# Distance-aware reward parameters
distance_reward:
  distance_bonus_factor: 0.1     # Bonus for optimal mode selection
  distance_penalty_factor: 0.05  # Penalty for suboptimal mode selection
  optimization_threshold: 0.7    # Threshold for mode change decisions

# Performance tracking
performance_tracking:
  enable_history: true       # Track distance and performance history
  history_length: 1000       # Maximum history length
  enable_adaptive_learning: true  # Enable adaptive learning from performance

# Distance categories and their characteristics
distance_categories:
  near:
    description: "Short-range communication (0-50m)"
    optimal_modes: [1, 2, 3]
    characteristics:
      - "High beam focus"
      - "Low crosstalk"
      - "High throughput potential"
      - "Sensitive to pointing errors"
  
  medium:
    description: "Medium-range communication (50-150m)"
    optimal_modes: [4, 5, 6]
    characteristics:
      - "Balanced performance"
      - "Moderate crosstalk"
      - "Good coverage"
      - "Stable operation"
  
  far:
    description: "Long-range communication (150m+)"
    optimal_modes: [7, 8]
    characteristics:
      - "Wide coverage"
      - "Higher crosstalk"
      - "Lower throughput"
      - "Robust to pointing errors"

# Optimization strategies
optimization_strategies:
  conservative:
    description: "Conservative mode selection (minimize handovers)"
    change_threshold: 0.8
    stability_weight: 0.4
    
  aggressive:
    description: "Aggressive mode selection (maximize throughput)"
    change_threshold: 0.5
    throughput_weight: 0.7
    
  balanced:
    description: "Balanced mode selection (default)"
    change_threshold: 0.7
    distance_weight: 0.3
    throughput_weight: 0.5
    stability_weight: 0.2

# Distance-based SINR thresholds
distance_sinr_thresholds:
  near: -3.0    # dB - Higher threshold for near distances
  medium: -5.0  # dB - Standard threshold for medium distances
  far: -7.0     # dB - Lower threshold for far distances

# Handover optimization
handover_optimization:
  enable_distance_aware_handover: true
  min_handover_interval: 5    # Minimum steps between handovers
  handover_hysteresis: 0.1    # Hysteresis to prevent ping-pong
  distance_based_handover_threshold: true 