# OAM 6G Hybrid Configuration - 100 Gbps Target
# Balanced approach: Medium range with optimized throughput
# Inherits from base_config_new.yaml

# Enhanced system parameters for 100 Gbps
system:
  # Expanded bandwidth for higher throughput
  bandwidth_bands:
    mmwave: 2e9         # 2 GHz (increased from 400 MHz)
    sub_thz_low: 20e9   # 20 GHz (increased from 4 GHz)
    sub_thz_high: 50e9  # 50 GHz (increased from 10 GHz)
  
  # Higher transmit power for better signal strength
  tx_power_dBm:
    mmwave: 40.0        # Increased from 30.0
    sub_thz_low: 30.0   # DOCOMO-like sanity (reduced)
    sub_thz_high: 60.0  # Increased from 45.0
  
  # Updated throughput targets
  max_throughput_gbps:
    mmwave: 10.0        # Increased from 2.0
    sub_thz_low: 50.0   # Increased from 20.0
    sub_thz_high: 100.0 # Target throughput
  
  # Required common parameters
  noise_figure_dB: 8.0       # 8 dB noise figure
  noise_temp: 290.0          # 290 K noise temperature

  # High-gain antennas assumed for sub-THz trials (directional arrays)
  tx_antenna_gain_dBi:
    mmwave: 25.0
    sub_thz_low: 20.0
    sub_thz_high: 45.0
  rx_antenna_gain_dBi:
    mmwave: 25.0
    sub_thz_low: 20.0
    sub_thz_high: 45.0

# Enhanced OAM parameters for higher frequencies
oam:
  # Required OAM parameters
  min_mode: 1                # Minimum OAM mode
  max_mode: 8                # Maximum OAM mode
  beam_width: 0.03           # Default beam width (mmWave)
  
  # Tighter beam widths for higher frequencies
  beam_width_bands:
    mmwave: 0.02        # Tighter beam (was 0.03)
    sub_thz_low: 0.004  # Very tight beam (was 0.006)
    sub_thz_high: 0.002 # Extremely tight beam (was 0.003)

# Balanced distance thresholds for 100 Gbps
hybrid_system:
  # Distance-based band selection (balanced approach)
  distance_thresholds:
    mmwave_max_distance: 150.0    # Reduced from 300.0
    sub_thz_low_max_distance: 75.0  # Reduced from 100.0
    sub_thz_high_max_distance: 30.0  # Reduced from 50.0
  
  # Performance thresholds for 100 Gbps
  performance_thresholds:
    throughput_threshold_gbps: 25.0  # Higher threshold
    sinr_threshold_dB: -8.0          # Stricter SINR requirement
    
  # Band selection strategy
  band_selection:
    strategy: "balanced_throughput"  # New strategy
    min_band_switch_interval: 20     # Increased from 10
    band_switch_hysteresis: 0.3      # Increased from 0.2

# Band-specific distance optimization for 100 Gbps
distance_optimization_bands:
  mmwave:
    near_threshold: 30.0      # Reduced from 50.0
    medium_threshold: 100.0    # Reduced from 150.0
    far_threshold: 150.0       # Reduced from 300.0
    near_modes: [1, 2, 3]
    medium_modes: [4, 5, 6]
    far_modes: [7, 8]
  
  sub_thz_low:
    near_threshold: 10.0       # Reduced from 10.0
    medium_threshold: 40.0     # Reduced from 50.0
    far_threshold: 75.0        # Reduced from 100.0
    near_modes: [1, 2, 3]
    medium_modes: [4, 5]
    far_modes: [6, 7, 8]
  
  sub_thz_high:
    near_threshold: 5.0        # Reduced from 5.0
    medium_threshold: 15.0     # Reduced from 25.0
    far_threshold: 30.0        # Reduced from 50.0
    near_modes: [1, 2]
    medium_modes: [3, 4]
    far_modes: [5, 6]

# Enhanced training parameters for 100 Gbps
training:
  num_episodes: 2000         # More episodes for complex system
  max_steps_per_episode: 250 # Shorter episodes for faster convergence
  batch_size: 512            # Larger batch for complex state space
  learning_rate: 0.00005     # Lower learning rate for stability
  gamma: 0.99                # Discount factor
  
  # Enhanced exploration for 100 Gbps
  exploration:
    epsilon_start: 1.0
    epsilon_end: 0.005       # Lower final epsilon
    epsilon_decay: 0.997     # Slower decay
    
  # Optimized band exploration
  band_exploration:
    initial_band_switch_prob: 0.2  # Reduced from 0.3
    final_band_switch_prob: 0.02   # Reduced from 0.05
    band_switch_decay: 0.9995      # Faster decay

# Enhanced reward parameters for 100 Gbps
reward:
  # Base rewards
  throughput_factor: 2.0     # Increased from 1.0 (prioritize throughput)
  handover_penalty: 0.1      # Reduced from 0.2 (less penalty)
  outage_penalty: 2.0        # Increased from 1.0 (stricter)
  sinr_threshold: -8.0       # Stricter from -5.0
  
  # Band-specific rewards for 100 Gbps
  band_rewards:
    mmwave:
      throughput_bonus: 0.1      # Small bonus
      range_bonus: 0.05          # Small range bonus
    sub_thz_low:
      throughput_bonus: 0.3      # Medium bonus
      range_bonus: 0.02          # Small range bonus
    sub_thz_high:
      throughput_bonus: 0.8      # Large bonus for 100 Gbps
      range_bonus: 0.0           # No range bonus (short range)
  
  # Band switching penalties
  band_switch_penalty: 0.3      # Reduced from 0.5
  band_switch_success_bonus: 0.5 # Increased from 0.3

# Enhanced evaluation parameters
evaluation:
  eval_episodes: 30            # More episodes for evaluation
  eval_frequency: 100          # Evaluate every 100 episodes
  save_model_frequency: 100    # Save every 100 episodes
  
  # Enhanced metrics for 100 Gbps
  metrics:
    throughput_by_band: true
    band_switch_frequency: true
    distance_performance: true
    power_efficiency: true
    throughput_target_achievement: true  # New metric

# Enhanced physics model for 100 Gbps
physics:
  # Improved atmospheric absorption modeling
  atmospheric_absorption:
    mmwave: 0.05              # Minimal absorption
    sub_thz_low: 1.5          # Moderate absorption
    sub_thz_high: 12.0        # High absorption (reduced from 15.0)
  
  # Optimized path loss exponents
  path_loss_exponents:
    mmwave: 2.2               # Reduced from 2.5
    sub_thz_low: 2.8          # Reduced from 3.0
    sub_thz_high: 3.2         # Reduced from 3.5
  
  # Enhanced beamforming for 100 Gbps
  beamforming:
    mmwave:
      beam_width: 0.02        # Tighter beam
      pointing_accuracy: 0.003 # More precise
    sub_thz_low:
      beam_width: 0.004       # Very tight beam
      pointing_accuracy: 0.001 # Ultra-precise
    sub_thz_high:
      beam_width: 0.002       # Extremely tight beam
      pointing_accuracy: 0.0005 # Maximum precision

# Enhanced mobility for 100 Gbps
mobility:
  # Optimized area sizes for higher frequencies
  area_size_bands:
    mmwave: [300.0, 300.0]   # Reduced from [500.0, 500.0]
    sub_thz_low: [150.0, 150.0]  # Reduced from [200.0, 200.0]
    sub_thz_high: [60.0, 60.0]   # Reduced from [100.0, 100.0]
  
  # Enhanced mobility parameters
  max_speed: 3.0              # Reduced from 5.0 (more stable)
  min_speed: 0.3              # Reduced from 0.5
  direction_change_prob: 0.05 # Reduced from 0.1 (more stable) 