# High-bandwidth sub-THz evaluation configuration (100 GHz, 10 GHz BW)

system:
  frequency: 1.00e11        # 100 GHz
  bandwidth: 1.00e10        # 10 GHz
  tx_power_dBm: 18.0        # Conservative sub-THz TX power
  noise_figure_dB: 10.0
  noise_temp: 290.0
  tx_antenna_gain_dBi: 30.0
  rx_antenna_gain_dBi: 30.0

oam:
  min_mode: 1
  max_mode: 8
  beam_width: 0.015         # 15 mrad narrower beam at higher freq

environment:
  humidity: 30.0            # Drier air improves attenuation
  temperature: 20.0
  pressure: 101.3
  turbulence_strength: 1e-14
  pointing_error_std: 0.004
  rician_k_factor: 8.0

physics:
  atmospheric_absorption_dB_per_km: 1.5   # Approximate at 100 GHz (moderate conditions)

training:
  learning_rate: 1.0e-3
  gamma: 0.99
  batch_size: 64
  target_update_freq: 100
  max_steps_per_episode: 200
  num_episodes: 10

network:
  hidden_layers: [128, 128]

handover_optimization:
  min_handover_interval: 12
  time_to_trigger_steps: 10
  handover_hysteresis_db: 3.0


