name: Environment Verification

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    paths:
      - 'config/requirements.txt'
      - 'setup.py'
      - 'pyproject.toml'

jobs:
  verify:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, '3.10']
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f config/requirements.txt ]; then pip install -r config/requirements.txt; fi
    - name: Verify environment
      run: |
        python scripts/verification/verify_environment.py
    - name: Test installation as package
      run: |
        pip install -e .
        python -c "import environment.oam_env; print('Import successful')"
        python -c "from models.agent import Agent; print('Import successful')"
        python -c "from simulator.channel_simulator import ChannelSimulator; print('Import successful')"