name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, '3.10']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f config/requirements.txt ]; then pip install -r config/requirements.txt; fi
        pip install pytest pytest-cov
        pip install -e .
    - name: Run unit tests
      run: |
        pytest tests/unit/ -v
    - name: Run integration tests
      run: |
        pytest tests/integration/ -v
    - name: Run regression tests
      run: |
        pytest tests/regression/ -v
    - name: Generate test report
      run: |
        pytest tests/ --junitxml=test-results.xml
    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: test-results-${{ matrix.python-version }}
        path: test-results.xml